services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.28
    container_name: elasticsearch
    restart: always
    environment: 
      - discovery.type=single-node #standalone mode
      - xpack.security.enabled=false #disable auth
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elastic
    
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.28
    container_name: kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.28
    container_name: logstash
    restart: always
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - 5000:5000
    depends_on:
      - elasticsearch
    networks:
      - elastic

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - 5678:5678
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=America/Sao_Paulo
    volumes:
      - n8n-data:/home/node/.n8n
      - ./local-files:/files
    networks:
      - elastic

  go-crypto:
    build:
      context: ./go-crypto
    container_name: go-crypto
    restart: always
    ports:
      - 8080:8080
    networks:
      - elastic
    depends_on:
      - logstash
    command: ["./main"]

networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch-data:
    driver: local
  n8n-data:
    driver: local